/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tera-dev' at '7/16/15 9:53 AM' with Gradle 2.5
 *
 * @author tera-dev, @date 7/16/15 9:53 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
